---
- hosts: all
  remote_user: root
  tasks:
    - name: theHarvester checkout
      git:
        repo: 'https://github.com/laramies/theHarvester'
        dest: ~/theHarvester
        update: no
    - name: disable reportgraph in theharvester
      lineinfile:
        path: theHarvester/theHarvester/__main__.py
        state: absent
        regexp: '^ +(graph = reportgraph\.GraphGenerator|HTMLcode \+= graph\.).*'
    - name: api keys
      template:
        src: templates/api-keys.yaml.j2
        dest: theHarvester/api-keys.yaml
    - name: build container
      shell: cd theHarvester && docker build . -t theharvester
    - name: theharvester script
      copy:
        src: scripts/theHarvester.sh
        dest: ~/theHarvester.sh
        mode: u+rwx
    - name: install amass
      shell: snap install amass
      args:
        creates: /snap/bin/amass
    - name: amass script
      copy:
        src: scripts/amass.sh
        dest: amass.sh
        mode: u+rwx
    - name: run amass
      shell: ./amass.sh {{ TARGET }}
      args:
        creates: "{{ TARGET }}.amass-results.tgz"
      async: 1000
      poll: 0
      register: amass
    - name: run theharvester
      shell: "./theHarvester.sh {{ TARGET }}"
      args:
        creates: "~/{{ TARGET }}.theHarvester-results.tgz"
      async: 1000
      poll: 0
      register: theharvester
    - name: amass check
      async_status:
        jid: "{{ amass.ansible_job_id }}"
      register: job_result
      until: job_result.finished
      delay: 15
      retries: 80
    - name: fetch amass output
      fetch:
        src: "{{ TARGET }}.amass-results.tgz"
        dest: output/{{ TARGET }}/
        flat: yes
    - name: theharvester check
      async_status:
        jid: "{{ theharvester.ansible_job_id }}"
      register: job_result
      until: job_result.finished
      delay: 15
      retries: 80
    - name: fetch theharvester output
      fetch:
        src:  "~/{{ TARGET }}.theHarvester-results.tgz"
        dest: output/{{ TARGET }}/
        flat: yes
